### ISSUE TITLE
support vue3?

### ISSUE THREAD

**Issue by fengluo2** [cmp-cc/vue-cookies#84]
Are you sure to support vue3? The sample example does not work.

**Comment by cmp-cc** [comment]
I need more information

**Comment by fengluo2** [comment]
https://github.com/cmp-cc/vue-cookies/blob/master/sample/welcome-v3.html
This,He can't work properly

**Comment by cmp-cc** [comment]
This is a simple example that can be opened directly from the browser without the http server

Is there an error message in f12?  You can copy it

**Comment by fengluo2** [comment]
oh.This is my problem. I moved the file to another place, causing it to fail to load cookies. js

**Comment by fengluo2** [comment]
wait，He still can't seem to work.
main.ts
```
......
const app = createApp(App)

app.use(router)
    .use(pinia)
    .use(VueCookies)
    .use(ElementPlus)
    .mount('#app')
......
```
test.vue
```
......
<el-button @click="test">test</el-button>
......
<script lang="ts" setup>

const test = () => {
  this.$cookies.set("a","b")
}
</script>
......
```
error
```
Uncaught TypeError: Cannot read properties of undefined (reading '$cookies')
    at test (test.vue:8:8)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at emit$1 (runtime-core.esm-bundler.js:718:9)
    at runtime-core.esm-bundler.js:7388:53
    at handleClick (use-button.ts:46:5)
    at createElementBlock.onClick._cache.<computed>._cache.<computed> (button.vue:73:2)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:339:9)
```

**Comment by cmp-cc** [comment]
This is not the Vue Options API or Composition API。You can learn from them

**Comment by fengluo2** [comment]
thank you.
I've run it successfully.
This gave me a better understanding of vue.
